version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # Add other environment variables from your .env file here
    restart: unless-stopped
    networks:
      - ragfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      # Add other environment variables from your .env file here
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ragfolio-network

networks:
  ragfolio-network:
    driver: bridge
