init:
	export GOOGLE_APPLICATION_CREDENTIALS="terraform.serviceaccount.json"
	terraform init -backend-config="bucket=terraform_statefiles_nishantlabs" -backend-config="prefix=ragfolio/terraform.state" 
