name: Build And Deploy

env:
  WORKLOAD_IDENTITY: 'projects/409209109459/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'container-pusher@personal-nishantlabs.iam.gserviceaccount.com'
  GCP_ARTIFACT_REGION: 'us-central1'
  GCP_PROJECT_ID: 'personal-nishantlabs'
  GCP_ARTIFACT_REGISTRY: 'ragfolio'
  IMAGE_NAME: 'ragfolio'
  WORKING_DIR: 'app'


on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - 'build and push'
        default: 'build and push' 

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: 'applierAuth'
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/authenticate-gcp
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY }}
          service_account: ${{ env.SERVICE_ACCOUNT }} 

      - name: 'Set up Cloud SDK'
        if: github.event_name == 'workflow_dispatch'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

      - name: Build and push Docker image to Google Artifact Registry
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          commit_id=$(git rev-parse HEAD)
          docker build -t \
            ${{ env.GCP_ARTIFACT_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${commit_id} .
          docker push us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${commit_id}
